format = """
[](#FFFFFF)\
$os\
$username\
[](bg:#F1D592 fg:#FFFFFF)\
$directory\
[](fg:#F1D592 bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$golang\
$nodejs\
$rust\
$lua\
$python\
[](fg:#86BBD8 bg:#06969A)\
$docker_context\
[](fg:#06969A bg:#33658A)\
$time\
[ ](fg:#33658A)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#FFFFFF"
style_root = "bg:#ff0000"
format = '[ $user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#FFFFFF"
disabled = false # Disabled by default

[os.symbols]
Macos = ""
Linux = "󰌽"
Debian = ""
Ubuntu = ""

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[  $time ]($style)'

[directory]
style = "bg:#F1D592"
format = "[  $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Tools
[docker_context]
symbol = " "
style = "bg:#4e8fe2"
format = '[ $symbol $context ]($style)'

[git_branch]
symbol = ""
style = "bg:#FCA17D"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'

# Language specific setup
[golang]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[lua]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "bg:#86BBD8"
python_binary = "python3"
format = '[ $symbol ($version) (\($virtualenv\)) ]($style)'
