return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      auto_install = true,
      ensure_installed = {
        "cmake",
        "csv",
        "dockerfile",
        "git_config",
        "gitignore",
        "go",
        "gomod",
        "gosum",
        "html",
        "http",
        "javascript",
        "json",
        "make",
        "markdown",
        "markdown_inline",
        "proto",
        "python",
        "scss",
        "ssh_config",
        "svelte",
        "terraform",
        "toml",
        "tsv",
        "typescript",
        "vim",
        "yaml",
      },
    },
  },
}
